import { SaleRecord } from '@/types/sales';

export const SAMPLE_SALES_RECORDS: SaleRecord[] = [
  {
    "id": 75,
    "order_id": "ORD-2026-1075",
    "date": "2026-08-20T14:07:47Z",
    "amount": 66405,
    "customer_name": "Naveen Gupta",
    "customer_email": "naveen.gupta@consultant.in",
    "customer_city": "Noida",
    "region": "North",
    "product_id": "PRD-112",
    "product_name": "Apple iPad Air M2 256GB",
    "category": "Electronics",
    "quantity": 1,
    "unit_price": 69900,
    "discount": 3495,
    "salesperson": "Kavita Rao",
    "payment_method": "Net Banking",
    "status": "pending",
    "notes": "Commercial transaction via Net Banking"
  },
  {
    "id": 1,
    "order_id": "ORD-2026-1001",
    "date": "2026-08-19T19:47:57Z",
    "amount": 71250,
    "customer_name": "HDFC Financial Services",
    "customer_email": "it.assets@hdfcbank.com",
    "customer_city": "Mumbai",
    "region": "West",
    "product_id": "PRD-111",
    "product_name": "Data Analytics Pipeline Connector Pro",
    "category": "SaaS Software",
    "quantity": 1,
    "unit_price": 75000,
    "discount": 3750,
    "salesperson": "Rahul Verma",
    "payment_method": "Net Banking",
    "status": "completed",
    "notes": "Commercial transaction via Net Banking"
  },
  {
    "id": 141,
    "order_id": "ORD-2026-1141",
    "date": "2026-08-19T13:28:42Z",
    "amount": 24500,
    "customer_name": "Infosys Digital Labs",
    "customer_email": "vendor@infosys.com",
    "customer_city": "Bengaluru",
    "region": "South",
    "product_id": "PRD-110",
    "product_name": "Bose SoundLink Revolve II Speaker",
    "category": "Audio",
    "quantity": 1,
    "unit_price": 24500,
    "discount": 0,
    "salesperson": "Rahul Verma",
    "payment_method": "Credit Card",
    "status": "completed",
    "notes": "Commercial transaction via Credit Card"
  },
  {
    "id": 76,
    "order_id": "ORD-2026-1076",
    "date": "2026-08-18T17:38:18Z",
    "amount": 42495,
    "customer_name": "Aarav Sharma",
    "customer_email": "aarav.s@gmail.com",
    "customer_city": "Delhi",
    "region": "North",
    "product_id": "PRD-109",
    "product_name": "Anker PowerStation 100W Fast Charger",
    "category": "Accessories",
    "quantity": 5,
    "unit_price": 8499,
    "discount": 0,
    "salesperson": "Ananya Sen",
    "payment_method": "Credit Card",
    "status": "cancelled",
    "notes": "Commercial transaction via Credit Card"
  },
  {
    "id": 2,
    "order_id": "ORD-2026-1002",
    "date": "2026-08-18T17:38:01Z",
    "amount": 8075,
    "customer_name": "Infosys Digital Labs",
    "customer_email": "vendor@infosys.com",
    "customer_city": "Bengaluru",
    "region": "South",
    "product_id": "PRD-109",
    "product_name": "Anker PowerStation 100W Fast Charger",
    "category": "Accessories",
    "quantity": 1,
    "unit_price": 8499,
    "discount": 424,
    "salesperson": "Rohan Mehta",
    "payment_method": "Debit Card",
    "status": "completed",
    "notes": "Commercial transaction via Debit Card"
  },
  {
    "id": 77,
    "order_id": "ORD-2026-1077",
    "date": "2026-08-17T20:34:08Z",
    "amount": 185000,
    "customer_name": "Priya Patel Enterprises",
    "customer_email": "priya@pateldesign.co",
    "customer_city": "Ahmedabad",
    "region": "West",
    "product_id": "PRD-102",
    "product_name": "Enterprise AI Cloud Subscription Annual",
    "category": "SaaS Software",
    "quantity": 1,
    "unit_price": 185000,
    "discount": 0,
    "salesperson": "Kavita Rao",
    "payment_method": "Credit Card",
    "status": "completed",
    "notes": "Commercial transaction via Credit Card"
  },
  {
    "id": 142,
    "order_id": "ORD-2026-1142",
    "date": "2026-08-17T10:22:27Z",
    "amount": 76475,
    "customer_name": "Deepika Sen",
    "customer_email": "deepika.sen@designhub.in",
    "customer_city": "Kolkata",
    "region": "East",
    "product_id": "PRD-107",
    "product_name": "Sony WH-1000XM5 Wireless Headphones",
    "category": "Audio",
    "quantity": 3,
    "unit_price": 29990,
    "discount": 13495,
    "salesperson": "Rohan Mehta",
    "payment_method": "Debit Card",
    "status": "refunded",
    "notes": "Commercial transaction via Debit Card"
  },
  {
    "id": 3,
    "order_id": "ORD-2026-1003",
    "date": "2026-08-17T09:48:51Z",
    "amount": 67992,
    "customer_name": "Priya Patel Enterprises",
    "customer_email": "priya@pateldesign.co",
    "customer_city": "Ahmedabad",
    "region": "West",
    "product_id": "PRD-109",
    "product_name": "Anker PowerStation 100W Fast Charger",
    "category": "Accessories",
    "quantity": 8,
    "unit_price": 8499,
    "discount": 0,
    "salesperson": "Rohan Mehta",
    "payment_method": "Debit Card",
    "status": "completed",
    "notes": "Commercial transaction via Debit Card"
  },
  {
    "id": 4,
    "order_id": "ORD-2026-1004",
    "date": "2026-08-16T14:06:05Z",
    "amount": 84500,
    "customer_name": "Bhubaneswar Softworks",
    "customer_email": "contact@bbsrsoft.com",
    "customer_city": "Bhubaneswar",
    "region": "East",
    "product_id": "PRD-103",
    "product_name": "Ergonomic Herman Miller Chair",
    "category": "Furniture",
    "quantity": 1,
    "unit_price": 84500,
    "discount": 0,
    "salesperson": "Kavita Rao",
    "payment_method": "Net Banking",
    "status": "completed",
    "notes": "Commercial transaction via Net Banking"
  },
  {
    "id": 143,
    "order_id": "ORD-2026-1143",
    "date": "2026-08-16T09:00:13Z",
    "amount": 157250,
    "customer_name": "Zomato Media Pvt Ltd",
    "customer_email": "infra@zomato.com",
    "customer_city": "Gurugram",
    "region": "North",
    "product_id": "PRD-102",
    "product_name": "Enterprise AI Cloud Subscription Annual",
    "category": "SaaS Software",
    "quantity": 1,
    "unit_price": 185000,
    "discount": 27750,
    "salesperson": "Rohan Mehta",
    "payment_method": "Debit Card",
    "status": "pending",
    "notes": "Commercial transaction via Debit Card"
  },
  {
    "id": 5,
    "order_id": "ORD-2026-1005",
    "date": "2026-08-15T17:07:59Z",
    "amount": 29990,
    "customer_name": "HDFC Financial Services",
    "customer_email": "it.assets@hdfcbank.com",
    "customer_city": "Mumbai",
    "region": "West",
    "product_id": "PRD-107",
    "product_name": "Sony WH-1000XM5 Wireless Headphones",
    "category": "Audio",
    "quantity": 1,
    "unit_price": 29990,
    "discount": 0,
    "salesperson": "Kavita Rao",
    "payment_method": "Net Banking",
    "status": "pending",
    "notes": "Commercial transaction via Net Banking"
  },
  {
    "id": 78,
    "order_id": "ORD-2026-1078",
    "date": "2026-08-15T16:06:55Z",
    "amount": 49999,
    "customer_name": "Tata Consultancy Services",
    "customer_email": "infra.buy@tcs.com",
    "customer_city": "Mumbai",
    "region": "West",
    "product_id": "PRD-105",
    "product_name": "SalesPulse CRM Enterprise License",
    "category": "SaaS Software",
    "quantity": 1,
    "unit_price": 49999,
    "discount": 0,
    "salesperson": "Rahul Verma",
    "payment_method": "Bank Transfer",
    "status": "pending",
    "notes": "Commercial transaction via Bank Transfer"
  },
  {
    "id": 144,
    "order_id": "ORD-2026-1144",
    "date": "2026-08-14T20:27:11Z",
    "amount": 45000,
    "customer_name": "Priya Patel Enterprises",
    "customer_email": "priya@pateldesign.co",
    "customer_city": "Ahmedabad",
    "region": "West",
    "product_id": "PRD-105",
    "product_name": "SalesPulse CRM Enterprise License",
    "category": "SaaS Software",
    "quantity": 1,
    "unit_price": 49999,
    "discount": 4999,
    "salesperson": "Ananya Sen",
    "payment_method": "Net Banking",
    "status": "pending",
    "notes": "Commercial transaction via Net Banking"
  },
  {
    "id": 79,
    "order_id": "ORD-2026-1079",
    "date": "2026-08-13T13:55:30Z",
    "amount": 303905,
    "customer_name": "Zomato Media Pvt Ltd",
    "customer_email": "infra@zomato.com",
    "customer_city": "Gurugram",
    "region": "North",
    "product_id": "PRD-101",
    "product_name": "MacBook Pro M3 Max 16-inch",
    "category": "Electronics",
    "quantity": 1,
    "unit_price": 319900,
    "discount": 15995,
    "salesperson": "Deepak Nair",
    "payment_method": "Debit Card",
    "status": "cancelled",
    "notes": "Commercial transaction via Debit Card"
  },
  {
    "id": 6,
    "order_id": "ORD-2026-1006",
    "date": "2026-08-13T09:42:14Z",
    "amount": 142453,
    "customer_name": "Infosys Digital Labs",
    "customer_email": "vendor@infosys.com",
    "customer_city": "Bengaluru",
    "region": "South",
    "product_id": "PRD-107",
    "product_name": "Sony WH-1000XM5 Wireless Headphones",
    "category": "Audio",
    "quantity": 5,
    "unit_price": 29990,
    "discount": 7497,
    "salesperson": "Rohan Mehta",
    "payment_method": "Net Banking",
    "status": "completed",
    "notes": "Commercial transaction via Net Banking"
  },
  {
    "id": 7,
    "order_id": "ORD-2026-1007",
    "date": "2026-08-12T14:10:23Z",
    "amount": 49999,
    "customer_name": "Infosys Digital Labs",
    "customer_email": "vendor@infosys.com",
    "customer_city": "Bengaluru",
    "region": "South",
    "product_id": "PRD-105",
    "product_name": "SalesPulse CRM Enterprise License",
    "category": "SaaS Software",
    "quantity": 1,
    "unit_price": 49999,
    "discount": 0,
    "salesperson": "Ananya Sen",
    "payment_method": "UPI",
    "status": "refunded",
    "notes": "Commercial transaction via UPI"
  },
  {
    "id": 80,
    "order_id": "ORD-2026-1080",
    "date": "2026-08-12T13:05:15Z",
    "amount": 157250,
    "customer_name": "Infosys Digital Labs",
    "customer_email": "vendor@infosys.com",
    "customer_city": "Bengaluru",
    "region": "South",
    "product_id": "PRD-102",
    "product_name": "Enterprise AI Cloud Subscription Annual",
    "category": "SaaS Software",
    "quantity": 1,
    "unit_price": 185000,
    "discount": 27750,
    "salesperson": "Deepak Nair",
    "payment_method": "Debit Card",
    "status": "completed",
    "notes": "Commercial transaction via Debit Card"
  },
  {
    "id": 8,
    "order_id": "ORD-2026-1008",
    "date": "2026-08-11T13:59:40Z",
    "amount": 37800,
    "customer_name": "Priya Patel Enterprises",
    "customer_email": "priya@pateldesign.co",
    "customer_city": "Ahmedabad",
    "region": "West",
    "product_id": "PRD-106",
    "product_name": "Standing Electric Desk Pro",
    "category": "Furniture",
    "quantity": 1,
    "unit_price": 42000,
    "discount": 4200,
    "salesperson": "Kavita Rao",
    "payment_method": "UPI",
    "status": "completed",
    "notes": "Commercial transaction via UPI"
  },
  {
    "id": 81,
    "order_id": "ORD-2026-1081",
    "date": "2026-08-10T16:19:55Z",
    "amount": 185000,
    "customer_name": "Bhubaneswar Softworks",
    "customer_email": "contact@bbsrsoft.com",
    "customer_city": "Bhubaneswar",
    "region": "East",
    "product_id": "PRD-102",
    "product_name": "Enterprise AI Cloud Subscription Annual",
    "category": "SaaS Software",
    "quantity": 1,
    "unit_price": 185000,
    "discount": 0,
    "salesperson": "Rohan Mehta",
    "payment_method": "Bank Transfer",
    "status": "completed",
    "notes": "Commercial transaction via Bank Transfer"
  },
  {
    "id": 9,
    "order_id": "ORD-2026-1009",
    "date": "2026-08-09T15:17:04Z",
    "amount": 69900,
    "customer_name": "Vikram Malhotra",
    "customer_email": "vikram.m@techstart.io",
    "customer_city": "Gurugram",
    "region": "North",
    "product_id": "PRD-112",
    "product_name": "Apple iPad Air M2 256GB",
    "category": "Electronics",
    "quantity": 1,
    "unit_price": 69900,
    "discount": 0,
    "salesperson": "Kavita Rao",
    "payment_method": "UPI",
    "status": "completed",
    "notes": "Commercial transaction via UPI"
  },
  {
    "id": 10,
    "order_id": "ORD-2026-1010",
    "date": "2026-08-08T13:08:15Z",
    "amount": 206700,
    "customer_name": "Razorpay Tech Labs",
    "customer_email": "hardware@razorpay.com",
    "customer_city": "Bengaluru",
    "region": "South",
    "product_id": "PRD-104",
    "product_name": "Dell UltraSharp 32-inch 4K USB-C Monitor",
    "category": "Electronics",
    "quantity": 3,
    "unit_price": 68900,
    "discount": 0,
    "salesperson": "Ananya Sen",
    "payment_method": "Debit Card",
    "status": "refunded",
    "notes": "Commercial transaction via Debit Card"
  },
  {
    "id": 82,
    "order_id": "ORD-2026-1082",
    "date": "2026-08-08T12:40:13Z",
    "amount": 24500,
    "customer_name": "Bhubaneswar Softworks",
    "customer_email": "contact@bbsrsoft.com",
    "customer_city": "Bhubaneswar",
    "region": "East",
    "product_id": "PRD-110",
    "product_name": "Bose SoundLink Revolve II Speaker",
    "category": "Audio",
    "quantity": 1,
    "unit_price": 24500,
    "discount": 0,
    "salesperson": "Kavita Rao",
    "payment_method": "Bank Transfer",
    "status": "completed",
    "notes": "Commercial transaction via Bank Transfer"
  },
  {
    "id": 11,
    "order_id": "ORD-2026-1011",
    "date": "2026-08-07T17:31:05Z",
    "amount": 132810,
    "customer_name": "Ananya Iyer",
    "customer_email": "ananya.iyer@creativestudio.in",
    "customer_city": "Chennai",
    "region": "South",
    "product_id": "PRD-112",
    "product_name": "Apple iPad Air M2 256GB",
    "category": "Electronics",
    "quantity": 2,
    "unit_price": 69900,
    "discount": 6990,
    "salesperson": "Rohan Mehta",
    "payment_method": "Debit Card",
    "status": "refunded",
    "notes": "Commercial transaction via Debit Card"
  },
  {
    "id": 83,
    "order_id": "ORD-2026-1083",
    "date": "2026-08-06T16:44:38Z",
    "amount": 45000,
    "customer_name": "Infosys Digital Labs",
    "customer_email": "vendor@infosys.com",
    "customer_city": "Bengaluru",
    "region": "South",
    "product_id": "PRD-105",
    "product_name": "SalesPulse CRM Enterprise License",
    "category": "SaaS Software",
    "quantity": 1,
    "unit_price": 49999,
    "discount": 4999,
    "salesperson": "Ananya Sen",
    "payment_method": "Credit Card",
    "status": "completed",
    "notes": "Commercial transaction via Credit Card"
  },
  {
    "id": 12,
    "order_id": "ORD-2026-1012",
    "date": "2026-08-05T18:29:33Z",
    "amount": 319900,
    "customer_name": "HDFC Financial Services",
    "customer_email": "it.assets@hdfcbank.com",
    "customer_city": "Mumbai",
    "region": "West",
    "product_id": "PRD-101",
    "product_name": "MacBook Pro M3 Max 16-inch",
    "category": "Electronics",
    "quantity": 1,
    "unit_price": 319900,
    "discount": 0,
    "salesperson": "Ananya Sen",
    "payment_method": "Credit Card",
    "status": "refunded",
    "notes": "Commercial transaction via Credit Card"
  },
  {
    "id": 84,
    "order_id": "ORD-2026-1084",
    "date": "2026-08-05T16:04:43Z",
    "amount": 94950,
    "customer_name": "Zomato Media Pvt Ltd",
    "customer_email": "infra@zomato.com",
    "customer_city": "Gurugram",
    "region": "North",
    "product_id": "PRD-108",
    "product_name": "Logitech MX Master 3S Combo",
    "category": "Accessories",
    "quantity": 5,
    "unit_price": 18990,
    "discount": 0,
    "salesperson": "Rahul Verma",
    "payment_method": "Credit Card",
    "status": "pending",
    "notes": "Commercial transaction via Credit Card"
  },
  {
    "id": 13,
    "order_id": "ORD-2026-1013",
    "date": "2026-08-04T11:29:00Z",
    "amount": 45000,
    "customer_name": "Reliance Retail Ltd",
    "customer_email": "procurement@reliance.in",
    "customer_city": "Mumbai",
    "region": "West",
    "product_id": "PRD-105",
    "product_name": "SalesPulse CRM Enterprise License",
    "category": "SaaS Software",
    "quantity": 1,
    "unit_price": 49999,
    "discount": 4999,
    "salesperson": "Rahul Verma",
    "payment_method": "Bank Transfer",
    "status": "pending",
    "notes": "Commercial transaction via Bank Transfer"
  },
  {
    "id": 85,
    "order_id": "ORD-2026-1085",
    "date": "2026-08-03T19:09:58Z",
    "amount": 68900,
    "customer_name": "Ananya Iyer",
    "customer_email": "ananya.iyer@creativestudio.in",
    "customer_city": "Chennai",
    "region": "South",
    "product_id": "PRD-104",
    "product_name": "Dell UltraSharp 32-inch 4K USB-C Monitor",
    "category": "Electronics",
    "quantity": 1,
    "unit_price": 68900,
    "discount": 0,
    "salesperson": "Rohan Mehta",
    "payment_method": "Credit Card",
    "status": "refunded",
    "notes": "Commercial transaction via Credit Card"
  },
  {
    "id": 14,
    "order_id": "ORD-2026-1014",
    "date": "2026-08-02T19:32:38Z",
    "amount": 209700,
    "customer_name": "Ananya Iyer",
    "customer_email": "ananya.iyer@creativestudio.in",
    "customer_city": "Chennai",
    "region": "South",
    "product_id": "PRD-112",
    "product_name": "Apple iPad Air M2 256GB",
    "category": "Electronics",
    "quantity": 3,
    "unit_price": 69900,
    "discount": 0,
    "salesperson": "Rohan Mehta",
    "payment_method": "Credit Card",
    "status": "completed",
    "notes": "Commercial transaction via Credit Card"
  },
  {
    "id": 86,
    "order_id": "ORD-2026-1086",
    "date": "2026-08-01T18:58:18Z",
    "amount": 49999,
    "customer_name": "Wipro Technologies",
    "customer_email": "tech.orders@wipro.com",
    "customer_city": "Bengaluru",
    "region": "South",
    "product_id": "PRD-105",
    "product_name": "SalesPulse CRM Enterprise License",
    "category": "SaaS Software",
    "quantity": 1,
    "unit_price": 49999,
    "discount": 0,
    "salesperson": "Rahul Verma",
    "payment_method": "UPI",
    "status": "completed",
    "notes": "Commercial transaction via UPI"
  },
  {
    "id": 15,
    "order_id": "ORD-2026-1015",
    "date": "2026-08-01T09:07:59Z",
    "amount": 206700,
    "customer_name": "Wipro Technologies",
    "customer_email": "tech.orders@wipro.com",
    "customer_city": "Bengaluru",
    "region": "South",
    "product_id": "PRD-104",
    "product_name": "Dell UltraSharp 32-inch 4K USB-C Monitor",
    "category": "Electronics",
    "quantity": 3,
    "unit_price": 68900,
    "discount": 0,
    "salesperson": "Kavita Rao",
    "payment_method": "Credit Card",
    "status": "completed",
    "notes": "Commercial transaction via Credit Card"
  },
  {
    "id": 87,
    "order_id": "ORD-2026-1087",
    "date": "2026-07-31T16:28:05Z",
    "amount": 94950,
    "customer_name": "HDFC Financial Services",
    "customer_email": "it.assets@hdfcbank.com",
    "customer_city": "Mumbai",
    "region": "West",
    "product_id": "PRD-108",
    "product_name": "Logitech MX Master 3S Combo",
    "category": "Accessories",
    "quantity": 5,
    "unit_price": 18990,
    "discount": 0,
    "salesperson": "Deepak Nair",
    "payment_method": "Net Banking",
    "status": "refunded",
    "notes": "Commercial transaction via Net Banking"
  },
  {
    "id": 16,
    "order_id": "ORD-2026-1016",
    "date": "2026-07-30T10:48:34Z",
    "amount": 37800,
    "customer_name": "Zomato Media Pvt Ltd",
    "customer_email": "infra@zomato.com",
    "customer_city": "Gurugram",
    "region": "North",
    "product_id": "PRD-106",
    "product_name": "Standing Electric Desk Pro",
    "category": "Furniture",
    "quantity": 1,
    "unit_price": 42000,
    "discount": 4200,
    "salesperson": "Ananya Sen",
    "payment_method": "UPI",
    "status": "completed",
    "notes": "Commercial transaction via UPI"
  },
  {
    "id": 88,
    "order_id": "ORD-2026-1088",
    "date": "2026-07-29T18:37:01Z",
    "amount": 20825,
    "customer_name": "Tata Consultancy Services",
    "customer_email": "infra.buy@tcs.com",
    "customer_city": "Mumbai",
    "region": "West",
    "product_id": "PRD-110",
    "product_name": "Bose SoundLink Revolve II Speaker",
    "category": "Audio",
    "quantity": 1,
    "unit_price": 24500,
    "discount": 3675,
    "salesperson": "Deepak Nair",
    "payment_method": "Net Banking",
    "status": "pending",
    "notes": "Commercial transaction via Net Banking"
  },
  {
    "id": 17,
    "order_id": "ORD-2026-1017",
    "date": "2026-07-29T18:27:13Z",
    "amount": 169000,
    "customer_name": "Wipro Technologies",
    "customer_email": "tech.orders@wipro.com",
    "customer_city": "Bengaluru",
    "region": "South",
    "product_id": "PRD-103",
    "product_name": "Ergonomic Herman Miller Chair",
    "category": "Furniture",
    "quantity": 2,
    "unit_price": 84500,
    "discount": 0,
    "salesperson": "Deepak Nair",
    "payment_method": "Bank Transfer",
    "status": "completed",
    "notes": "Commercial transaction via Bank Transfer"
  },
  {
    "id": 89,
    "order_id": "ORD-2026-1089",
    "date": "2026-07-27T16:58:17Z",
    "amount": 150000,
    "customer_name": "Ananya Iyer",
    "customer_email": "ananya.iyer@creativestudio.in",
    "customer_city": "Chennai",
    "region": "South",
    "product_id": "PRD-111",
    "product_name": "Data Analytics Pipeline Connector Pro",
    "category": "SaaS Software",
    "quantity": 2,
    "unit_price": 75000,
    "discount": 0,
    "salesperson": "Rohan Mehta",
    "payment_method": "UPI",
    "status": "completed",
    "notes": "Commercial transaction via UPI"
  },
  {
    "id": 18,
    "order_id": "ORD-2026-1018",
    "date": "2026-07-27T16:07:15Z",
    "amount": 67992,
    "customer_name": "Priya Patel Enterprises",
    "customer_email": "priya@pateldesign.co",
    "customer_city": "Ahmedabad",
    "region": "West",
    "product_id": "PRD-109",
    "product_name": "Anker PowerStation 100W Fast Charger",
    "category": "Accessories",
    "quantity": 8,
    "unit_price": 8499,
    "discount": 0,
    "salesperson": "Kavita Rao",
    "payment_method": "Debit Card",
    "status": "completed",
    "notes": "Commercial transaction via Debit Card"
  },
  {
    "id": 19,
    "order_id": "ORD-2026-1019",
    "date": "2026-07-26T20:40:03Z",
    "amount": 196365,
    "customer_name": "Infosys Digital Labs",
    "customer_email": "vendor@infosys.com",
    "customer_city": "Bengaluru",
    "region": "South",
    "product_id": "PRD-104",
    "product_name": "Dell UltraSharp 32-inch 4K USB-C Monitor",
    "category": "Electronics",
    "quantity": 3,
    "unit_price": 68900,
    "discount": 10335,
    "salesperson": "Kavita Rao",
    "payment_method": "UPI",
    "status": "completed",
    "notes": "Commercial transaction via UPI"
  },
  {
    "id": 20,
    "order_id": "ORD-2026-1020",
    "date": "2026-07-25T16:13:34Z",
    "amount": 175695,
    "customer_name": "Infosys Digital Labs",
    "customer_email": "vendor@infosys.com",
    "customer_city": "Bengaluru",
    "region": "South",
    "product_id": "PRD-104",
    "product_name": "Dell UltraSharp 32-inch 4K USB-C Monitor",
    "category": "Electronics",
    "quantity": 3,
    "unit_price": 68900,
    "discount": 31005,
    "salesperson": "Rahul Verma",
    "payment_method": "Net Banking",
    "status": "completed",
    "notes": "Commercial transaction via Net Banking"
  },
  {
    "id": 90,
    "order_id": "ORD-2026-1090",
    "date": "2026-07-25T14:42:06Z",
    "amount": 169000,
    "customer_name": "Bhubaneswar Softworks",
    "customer_email": "contact@bbsrsoft.com",
    "customer_city": "Bhubaneswar",
    "region": "East",
    "product_id": "PRD-103",
    "product_name": "Ergonomic Herman Miller Chair",
    "category": "Furniture",
    "quantity": 2,
    "unit_price": 84500,
    "discount": 0,
    "salesperson": "Deepak Nair",
    "payment_method": "UPI",
    "status": "cancelled",
    "notes": "Commercial transaction via UPI"
  },
  {
    "id": 91,
    "order_id": "ORD-2026-1091",
    "date": "2026-07-24T17:02:29Z",
    "amount": 169000,
    "customer_name": "Razorpay Tech Labs",
    "customer_email": "hardware@razorpay.com",
    "customer_city": "Bengaluru",
    "region": "South",
    "product_id": "PRD-103",
    "product_name": "Ergonomic Herman Miller Chair",
    "category": "Furniture",
    "quantity": 2,
    "unit_price": 84500,
    "discount": 0,
    "salesperson": "Deepak Nair",
    "payment_method": "Debit Card",
    "status": "pending",
    "notes": "Commercial transaction via Debit Card"
  },
  {
    "id": 21,
    "order_id": "ORD-2026-1021",
    "date": "2026-07-23T15:22:27Z",
    "amount": 71825,
    "customer_name": "Deepika Sen",
    "customer_email": "deepika.sen@designhub.in",
    "customer_city": "Kolkata",
    "region": "East",
    "product_id": "PRD-103",
    "product_name": "Ergonomic Herman Miller Chair",
    "category": "Furniture",
    "quantity": 1,
    "unit_price": 84500,
    "discount": 12675,
    "salesperson": "Ananya Sen",
    "payment_method": "Debit Card",
    "status": "refunded",
    "notes": "Commercial transaction via Debit Card"
  },
  {
    "id": 22,
    "order_id": "ORD-2026-1022",
    "date": "2026-07-22T10:15:12Z",
    "amount": 119960,
    "customer_name": "Naveen Gupta",
    "customer_email": "naveen.gupta@consultant.in",
    "customer_city": "Noida",
    "region": "North",
    "product_id": "PRD-107",
    "product_name": "Sony WH-1000XM5 Wireless Headphones",
    "category": "Audio",
    "quantity": 4,
    "unit_price": 29990,
    "discount": 0,
    "salesperson": "Rahul Verma",
    "payment_method": "UPI",
    "status": "completed",
    "notes": "Commercial transaction via UPI"
  },
  {
    "id": 92,
    "order_id": "ORD-2026-1092",
    "date": "2026-07-22T09:42:55Z",
    "amount": 185000,
    "customer_name": "Razorpay Tech Labs",
    "customer_email": "hardware@razorpay.com",
    "customer_city": "Bengaluru",
    "region": "South",
    "product_id": "PRD-102",
    "product_name": "Enterprise AI Cloud Subscription Annual",
    "category": "SaaS Software",
    "quantity": 1,
    "unit_price": 185000,
    "discount": 0,
    "salesperson": "Kavita Rao",
    "payment_method": "Net Banking",
    "status": "completed",
    "notes": "Commercial transaction via Net Banking"
  },
  {
    "id": 93,
    "order_id": "ORD-2026-1093",
    "date": "2026-07-20T16:40:28Z",
    "amount": 76491,
    "customer_name": "Naveen Gupta",
    "customer_email": "naveen.gupta@consultant.in",
    "customer_city": "Noida",
    "region": "North",
    "product_id": "PRD-109",
    "product_name": "Anker PowerStation 100W Fast Charger",
    "category": "Accessories",
    "quantity": 9,
    "unit_price": 8499,
    "discount": 0,
    "salesperson": "Deepak Nair",
    "payment_method": "UPI",
    "status": "completed",
    "notes": "Commercial transaction via UPI"
  },
  {
    "id": 23,
    "order_id": "ORD-2026-1023",
    "date": "2026-07-20T10:28:51Z",
    "amount": 137800,
    "customer_name": "Naveen Gupta",
    "customer_email": "naveen.gupta@consultant.in",
    "customer_city": "Noida",
    "region": "North",
    "product_id": "PRD-104",
    "product_name": "Dell UltraSharp 32-inch 4K USB-C Monitor",
    "category": "Electronics",
    "quantity": 2,
    "unit_price": 68900,
    "discount": 0,
    "salesperson": "Ananya Sen",
    "payment_method": "Debit Card",
    "status": "completed",
    "notes": "Commercial transaction via Debit Card"
  },
  {
    "id": 24,
    "order_id": "ORD-2026-1024",
    "date": "2026-07-19T12:10:26Z",
    "amount": 16998,
    "customer_name": "HDFC Financial Services",
    "customer_email": "it.assets@hdfcbank.com",
    "customer_city": "Mumbai",
    "region": "West",
    "product_id": "PRD-109",
    "product_name": "Anker PowerStation 100W Fast Charger",
    "category": "Accessories",
    "quantity": 2,
    "unit_price": 8499,
    "discount": 0,
    "salesperson": "Rahul Verma",
    "payment_method": "Bank Transfer",
    "status": "completed",
    "notes": "Commercial transaction via Bank Transfer"
  },
  {
    "id": 94,
    "order_id": "ORD-2026-1094",
    "date": "2026-07-18T20:31:07Z",
    "amount": 319900,
    "customer_name": "Priya Patel Enterprises",
    "customer_email": "priya@pateldesign.co",
    "customer_city": "Ahmedabad",
    "region": "West",
    "product_id": "PRD-101",
    "product_name": "MacBook Pro M3 Max 16-inch",
    "category": "Electronics",
    "quantity": 1,
    "unit_price": 319900,
    "discount": 0,
    "salesperson": "Kavita Rao",
    "payment_method": "Bank Transfer",
    "status": "completed",
    "notes": "Commercial transaction via Bank Transfer"
  },
  {
    "id": 95,
    "order_id": "ORD-2026-1095",
    "date": "2026-07-17T16:07:41Z",
    "amount": 303905,
    "customer_name": "Vikram Malhotra",
    "customer_email": "vikram.m@techstart.io",
    "customer_city": "Gurugram",
    "region": "North",
    "product_id": "PRD-101",
    "product_name": "MacBook Pro M3 Max 16-inch",
    "category": "Electronics",
    "quantity": 1,
    "unit_price": 319900,
    "discount": 15995,
    "salesperson": "Ananya Sen",
    "payment_method": "Net Banking",
    "status": "completed",
    "notes": "Commercial transaction via Net Banking"
  },
  {
    "id": 25,
    "order_id": "ORD-2026-1025",
    "date": "2026-07-17T15:16:59Z",
    "amount": 56970,
    "customer_name": "Deepika Sen",
    "customer_email": "deepika.sen@designhub.in",
    "customer_city": "Kolkata",
    "region": "East",
    "product_id": "PRD-108",
    "product_name": "Logitech MX Master 3S Combo",
    "category": "Accessories",
    "quantity": 3,
    "unit_price": 18990,
    "discount": 0,
    "salesperson": "Ananya Sen",
    "payment_method": "Debit Card",
    "status": "completed",
    "notes": "Commercial transaction via Debit Card"
  },
  {
    "id": 96,
    "order_id": "ORD-2026-1096",
    "date": "2026-07-15T16:15:29Z",
    "amount": 169000,
    "customer_name": "Deepika Sen",
    "customer_email": "deepika.sen@designhub.in",
    "customer_city": "Kolkata",
    "region": "East",
    "product_id": "PRD-103",
    "product_name": "Ergonomic Herman Miller Chair",
    "category": "Furniture",
    "quantity": 2,
    "unit_price": 84500,
    "discount": 0,
    "salesperson": "Kavita Rao",
    "payment_method": "Bank Transfer",
    "status": "pending",
    "notes": "Commercial transaction via Bank Transfer"
  },
  {
    "id": 26,
    "order_id": "ORD-2026-1026",
    "date": "2026-07-15T09:37:47Z",
    "amount": 54122,
    "customer_name": "Zomato Media Pvt Ltd",
    "customer_email": "infra@zomato.com",
    "customer_city": "Gurugram",
    "region": "North",
    "product_id": "PRD-108",
    "product_name": "Logitech MX Master 3S Combo",
    "category": "Accessories",
    "quantity": 3,
    "unit_price": 18990,
    "discount": 2848,
    "salesperson": "Deepak Nair",
    "payment_method": "Bank Transfer",
    "status": "cancelled",
    "notes": "Commercial transaction via Bank Transfer"
  },
  {
    "id": 27,
    "order_id": "ORD-2026-1027",
    "date": "2026-07-14T17:10:03Z",
    "amount": 84990,
    "customer_name": "Tata Consultancy Services",
    "customer_email": "infra.buy@tcs.com",
    "customer_city": "Mumbai",
    "region": "West",
    "product_id": "PRD-109",
    "product_name": "Anker PowerStation 100W Fast Charger",
    "category": "Accessories",
    "quantity": 10,
    "unit_price": 8499,
    "discount": 0,
    "salesperson": "Kavita Rao",
    "payment_method": "UPI",
    "status": "completed",
    "notes": "Commercial transaction via UPI"
  },
  {
    "id": 97,
    "order_id": "ORD-2026-1097",
    "date": "2026-07-13T15:21:59Z",
    "amount": 16998,
    "customer_name": "Wipro Technologies",
    "customer_email": "tech.orders@wipro.com",
    "customer_city": "Bengaluru",
    "region": "South",
    "product_id": "PRD-109",
    "product_name": "Anker PowerStation 100W Fast Charger",
    "category": "Accessories",
    "quantity": 2,
    "unit_price": 8499,
    "discount": 0,
    "salesperson": "Deepak Nair",
    "payment_method": "Credit Card",
    "status": "completed",
    "notes": "Commercial transaction via Credit Card"
  },
  {
    "id": 28,
    "order_id": "ORD-2026-1028",
    "date": "2026-07-12T15:07:56Z",
    "amount": 93489,
    "customer_name": "Infosys Digital Labs",
    "customer_email": "vendor@infosys.com",
    "customer_city": "Bengaluru",
    "region": "South",
    "product_id": "PRD-109",
    "product_name": "Anker PowerStation 100W Fast Charger",
    "category": "Accessories",
    "quantity": 11,
    "unit_price": 8499,
    "discount": 0,
    "salesperson": "Ananya Sen",
    "payment_method": "UPI",
    "status": "completed",
    "notes": "Commercial transaction via UPI"
  },
  {
    "id": 98,
    "order_id": "ORD-2026-1098",
    "date": "2026-07-11T19:31:55Z",
    "amount": 84990,
    "customer_name": "Ananya Iyer",
    "customer_email": "ananya.iyer@creativestudio.in",
    "customer_city": "Chennai",
    "region": "South",
    "product_id": "PRD-109",
    "product_name": "Anker PowerStation 100W Fast Charger",
    "category": "Accessories",
    "quantity": 10,
    "unit_price": 8499,
    "discount": 0,
    "salesperson": "Rahul Verma",
    "payment_method": "Net Banking",
    "status": "pending",
    "notes": "Commercial transaction via Net Banking"
  },
  {
    "id": 29,
    "order_id": "ORD-2026-1029",
    "date": "2026-07-11T18:36:33Z",
    "amount": 24500,
    "customer_name": "Vikram Malhotra",
    "customer_email": "vikram.m@techstart.io",
    "customer_city": "Gurugram",
    "region": "North",
    "product_id": "PRD-110",
    "product_name": "Bose SoundLink Revolve II Speaker",
    "category": "Audio",
    "quantity": 1,
    "unit_price": 24500,
    "discount": 0,
    "salesperson": "Rohan Mehta",
    "payment_method": "Bank Transfer",
    "status": "completed",
    "notes": "Commercial transaction via Bank Transfer"
  },
  {
    "id": 99,
    "order_id": "ORD-2026-1099",
    "date": "2026-07-10T17:24:29Z",
    "amount": 169000,
    "customer_name": "Naveen Gupta",
    "customer_email": "naveen.gupta@consultant.in",
    "customer_city": "Noida",
    "region": "North",
    "product_id": "PRD-103",
    "product_name": "Ergonomic Herman Miller Chair",
    "category": "Furniture",
    "quantity": 2,
    "unit_price": 84500,
    "discount": 0,
    "salesperson": "Rohan Mehta",
    "payment_method": "Debit Card",
    "status": "completed",
    "notes": "Commercial transaction via Debit Card"
  },
  {
    "id": 30,
    "order_id": "ORD-2026-1030",
    "date": "2026-07-09T19:41:19Z",
    "amount": 84000,
    "customer_name": "Ananya Iyer",
    "customer_email": "ananya.iyer@creativestudio.in",
    "customer_city": "Chennai",
    "region": "South",
    "product_id": "PRD-106",
    "product_name": "Standing Electric Desk Pro",
    "category": "Furniture",
    "quantity": 2,
    "unit_price": 42000,
    "discount": 0,
    "salesperson": "Ananya Sen",
    "payment_method": "Net Banking",
    "status": "completed",
    "notes": "Commercial transaction via Net Banking"
  },
  {
    "id": 31,
    "order_id": "ORD-2026-1031",
    "date": "2026-07-08T17:16:08Z",
    "amount": 36081,
    "customer_name": "Razorpay Tech Labs",
    "customer_email": "hardware@razorpay.com",
    "customer_city": "Bengaluru",
    "region": "South",
    "product_id": "PRD-108",
    "product_name": "Logitech MX Master 3S Combo",
    "category": "Accessories",
    "quantity": 2,
    "unit_price": 18990,
    "discount": 1899,
    "salesperson": "Rahul Verma",
    "payment_method": "UPI",
    "status": "cancelled",
    "notes": "Commercial transaction via UPI"
  },
  {
    "id": 100,
    "order_id": "ORD-2026-1100",
    "date": "2026-07-08T15:02:20Z",
    "amount": 42000,
    "customer_name": "Priya Patel Enterprises",
    "customer_email": "priya@pateldesign.co",
    "customer_city": "Ahmedabad",
    "region": "West",
    "product_id": "PRD-106",
    "product_name": "Standing Electric Desk Pro",
    "category": "Furniture",
    "quantity": 1,
    "unit_price": 42000,
    "discount": 0,
    "salesperson": "Ananya Sen",
    "payment_method": "Bank Transfer",
    "status": "refunded",
    "notes": "Commercial transaction via Bank Transfer"
  },
  {
    "id": 32,
    "order_id": "ORD-2026-1032",
    "date": "2026-07-06T17:45:19Z",
    "amount": 42000,
    "customer_name": "Infosys Digital Labs",
    "customer_email": "vendor@infosys.com",
    "customer_city": "Bengaluru",
    "region": "South",
    "product_id": "PRD-106",
    "product_name": "Standing Electric Desk Pro",
    "category": "Furniture",
    "quantity": 1,
    "unit_price": 42000,
    "discount": 0,
    "salesperson": "Ananya Sen",
    "payment_method": "Net Banking",
    "status": "pending",
    "notes": "Commercial transaction via Net Banking"
  },
  {
    "id": 101,
    "order_id": "ORD-2026-1101",
    "date": "2026-07-06T11:32:37Z",
    "amount": 139800,
    "customer_name": "Deepika Sen",
    "customer_email": "deepika.sen@designhub.in",
    "customer_city": "Kolkata",
    "region": "East",
    "product_id": "PRD-112",
    "product_name": "Apple iPad Air M2 256GB",
    "category": "Electronics",
    "quantity": 2,
    "unit_price": 69900,
    "discount": 0,
    "salesperson": "Deepak Nair",
    "payment_method": "Debit Card",
    "status": "completed",
    "notes": "Commercial transaction via Debit Card"
  },
  {
    "id": 102,
    "order_id": "ORD-2026-1102",
    "date": "2026-07-05T15:55:41Z",
    "amount": 42000,
    "customer_name": "HDFC Financial Services",
    "customer_email": "it.assets@hdfcbank.com",
    "customer_city": "Mumbai",
    "region": "West",
    "product_id": "PRD-106",
    "product_name": "Standing Electric Desk Pro",
    "category": "Furniture",
    "quantity": 1,
    "unit_price": 42000,
    "discount": 0,
    "salesperson": "Deepak Nair",
    "payment_method": "UPI",
    "status": "cancelled",
    "notes": "Commercial transaction via UPI"
  },
  {
    "id": 33,
    "order_id": "ORD-2026-1033",
    "date": "2026-07-05T10:47:35Z",
    "amount": 49000,
    "customer_name": "Reliance Retail Ltd",
    "customer_email": "procurement@reliance.in",
    "customer_city": "Mumbai",
    "region": "West",
    "product_id": "PRD-110",
    "product_name": "Bose SoundLink Revolve II Speaker",
    "category": "Audio",
    "quantity": 2,
    "unit_price": 24500,
    "discount": 0,
    "salesperson": "Rohan Mehta",
    "payment_method": "Net Banking",
    "status": "completed",
    "notes": "Commercial transaction via Net Banking"
  },
  {
    "id": 103,
    "order_id": "ORD-2026-1103",
    "date": "2026-07-03T14:54:43Z",
    "amount": 169000,
    "customer_name": "Infosys Digital Labs",
    "customer_email": "vendor@infosys.com",
    "customer_city": "Bengaluru",
    "region": "South",
    "product_id": "PRD-103",
    "product_name": "Ergonomic Herman Miller Chair",
    "category": "Furniture",
    "quantity": 2,
    "unit_price": 84500,
    "discount": 0,
    "salesperson": "Deepak Nair",
    "payment_method": "Net Banking",
    "status": "completed",
    "notes": "Commercial transaction via Net Banking"
  },
  {
    "id": 34,
    "order_id": "ORD-2026-1034",
    "date": "2026-07-03T13:32:31Z",
    "amount": 143650,
    "customer_name": "Ananya Iyer",
    "customer_email": "ananya.iyer@creativestudio.in",
    "customer_city": "Chennai",
    "region": "South",
    "product_id": "PRD-103",
    "product_name": "Ergonomic Herman Miller Chair",
    "category": "Furniture",
    "quantity": 2,
    "unit_price": 84500,
    "discount": 25350,
    "salesperson": "Kavita Rao",
    "payment_method": "Bank Transfer",
    "status": "completed",
    "notes": "Commercial transaction via Bank Transfer"
  },
  {
    "id": 35,
    "order_id": "ORD-2026-1035",
    "date": "2026-07-02T19:16:10Z",
    "amount": 47500,
    "customer_name": "Tata Consultancy Services",
    "customer_email": "infra.buy@tcs.com",
    "customer_city": "Mumbai",
    "region": "West",
    "product_id": "PRD-105",
    "product_name": "SalesPulse CRM Enterprise License",
    "category": "SaaS Software",
    "quantity": 1,
    "unit_price": 49999,
    "discount": 2499,
    "salesperson": "Rahul Verma",
    "payment_method": "Debit Card",
    "status": "pending",
    "notes": "Commercial transaction via Debit Card"
  },
  {
    "id": 104,
    "order_id": "ORD-2026-1104",
    "date": "2026-07-01T19:58:18Z",
    "amount": 72242,
    "customer_name": "Kolkata Port Logistics",
    "customer_email": "ops@kplogistics.in",
    "customer_city": "Kolkata",
    "region": "East",
    "product_id": "PRD-109",
    "product_name": "Anker PowerStation 100W Fast Charger",
    "category": "Accessories",
    "quantity": 10,
    "unit_price": 8499,
    "discount": 12748,
    "salesperson": "Kavita Rao",
    "payment_method": "Debit Card",
    "status": "completed",
    "notes": "Commercial transaction via Debit Card"
  },
  {
    "id": 36,
    "order_id": "ORD-2026-1036",
    "date": "2026-06-30T11:34:02Z",
    "amount": 59415,
    "customer_name": "Naveen Gupta",
    "customer_email": "naveen.gupta@consultant.in",
    "customer_city": "Noida",
    "region": "North",
    "product_id": "PRD-112",
    "product_name": "Apple iPad Air M2 256GB",
    "category": "Electronics",
    "quantity": 1,
    "unit_price": 69900,
    "discount": 10485,
    "salesperson": "Rohan Mehta",
    "payment_method": "Debit Card",
    "status": "completed",
    "notes": "Commercial transaction via Debit Card"
  },
  {
    "id": 105,
    "order_id": "ORD-2026-1105",
    "date": "2026-06-29T09:02:20Z",
    "amount": 124020,
    "customer_name": "Infosys Digital Labs",
    "customer_email": "vendor@infosys.com",
    "customer_city": "Bengaluru",
    "region": "South",
    "product_id": "PRD-104",
    "product_name": "Dell UltraSharp 32-inch 4K USB-C Monitor",
    "category": "Electronics",
    "quantity": 2,
    "unit_price": 68900,
    "discount": 13780,
    "salesperson": "Deepak Nair",
    "payment_method": "UPI",
    "status": "completed",
    "notes": "Commercial transaction via UPI"
  },
  {
    "id": 106,
    "order_id": "ORD-2026-1106",
    "date": "2026-06-28T18:43:50Z",
    "amount": 287910,
    "customer_name": "Zomato Media Pvt Ltd",
    "customer_email": "infra@zomato.com",
    "customer_city": "Gurugram",
    "region": "North",
    "product_id": "PRD-101",
    "product_name": "MacBook Pro M3 Max 16-inch",
    "category": "Electronics",
    "quantity": 1,
    "unit_price": 319900,
    "discount": 31990,
    "salesperson": "Kavita Rao",
    "payment_method": "Net Banking",
    "status": "refunded",
    "notes": "Commercial transaction via Net Banking"
  },
  {
    "id": 37,
    "order_id": "ORD-2026-1037",
    "date": "2026-06-28T09:57:22Z",
    "amount": 84000,
    "customer_name": "Wipro Technologies",
    "customer_email": "tech.orders@wipro.com",
    "customer_city": "Bengaluru",
    "region": "South",
    "product_id": "PRD-106",
    "product_name": "Standing Electric Desk Pro",
    "category": "Furniture",
    "quantity": 2,
    "unit_price": 42000,
    "discount": 0,
    "salesperson": "Deepak Nair",
    "payment_method": "Credit Card",
    "status": "completed",
    "notes": "Commercial transaction via Credit Card"
  },
  {
    "id": 38,
    "order_id": "ORD-2026-1038",
    "date": "2026-06-27T12:55:10Z",
    "amount": 206700,
    "customer_name": "Vikram Malhotra",
    "customer_email": "vikram.m@techstart.io",
    "customer_city": "Gurugram",
    "region": "North",
    "product_id": "PRD-104",
    "product_name": "Dell UltraSharp 32-inch 4K USB-C Monitor",
    "category": "Electronics",
    "quantity": 3,
    "unit_price": 68900,
    "discount": 0,
    "salesperson": "Rahul Verma",
    "payment_method": "Net Banking",
    "status": "refunded",
    "notes": "Commercial transaction via Net Banking"
  },
  {
    "id": 107,
    "order_id": "ORD-2026-1107",
    "date": "2026-06-26T18:09:14Z",
    "amount": 84500,
    "customer_name": "Aarav Sharma",
    "customer_email": "aarav.s@gmail.com",
    "customer_city": "Delhi",
    "region": "North",
    "product_id": "PRD-103",
    "product_name": "Ergonomic Herman Miller Chair",
    "category": "Furniture",
    "quantity": 1,
    "unit_price": 84500,
    "discount": 0,
    "salesperson": "Ananya Sen",
    "payment_method": "UPI",
    "status": "refunded",
    "notes": "Commercial transaction via UPI"
  },
  {
    "id": 39,
    "order_id": "ORD-2026-1039",
    "date": "2026-06-25T20:51:15Z",
    "amount": 169000,
    "customer_name": "Bhubaneswar Softworks",
    "customer_email": "contact@bbsrsoft.com",
    "customer_city": "Bhubaneswar",
    "region": "East",
    "product_id": "PRD-103",
    "product_name": "Ergonomic Herman Miller Chair",
    "category": "Furniture",
    "quantity": 2,
    "unit_price": 84500,
    "discount": 0,
    "salesperson": "Rahul Verma",
    "payment_method": "Credit Card",
    "status": "completed",
    "notes": "Commercial transaction via Credit Card"
  },
  {
    "id": 108,
    "order_id": "ORD-2026-1108",
    "date": "2026-06-24T19:34:10Z",
    "amount": 151920,
    "customer_name": "Ananya Iyer",
    "customer_email": "ananya.iyer@creativestudio.in",
    "customer_city": "Chennai",
    "region": "South",
    "product_id": "PRD-108",
    "product_name": "Logitech MX Master 3S Combo",
    "category": "Accessories",
    "quantity": 8,
    "unit_price": 18990,
    "discount": 0,
    "salesperson": "Deepak Nair",
    "payment_method": "Net Banking",
    "status": "completed",
    "notes": "Commercial transaction via Net Banking"
  },
  {
    "id": 40,
    "order_id": "ORD-2026-1040",
    "date": "2026-06-24T14:19:52Z",
    "amount": 45000,
    "customer_name": "Aarav Sharma",
    "customer_email": "aarav.s@gmail.com",
    "customer_city": "Delhi",
    "region": "North",
    "product_id": "PRD-105",
    "product_name": "SalesPulse CRM Enterprise License",
    "category": "SaaS Software",
    "quantity": 1,
    "unit_price": 49999,
    "discount": 4999,
    "salesperson": "Rahul Verma",
    "payment_method": "Debit Card",
    "status": "completed",
    "notes": "Commercial transaction via Debit Card"
  },
  {
    "id": 109,
    "order_id": "ORD-2026-1109",
    "date": "2026-06-22T16:54:19Z",
    "amount": 185000,
    "customer_name": "Naveen Gupta",
    "customer_email": "naveen.gupta@consultant.in",
    "customer_city": "Noida",
    "region": "North",
    "product_id": "PRD-102",
    "product_name": "Enterprise AI Cloud Subscription Annual",
    "category": "SaaS Software",
    "quantity": 1,
    "unit_price": 185000,
    "discount": 0,
    "salesperson": "Kavita Rao",
    "payment_method": "Bank Transfer",
    "status": "pending",
    "notes": "Commercial transaction via Bank Transfer"
  },
  {
    "id": 41,
    "order_id": "ORD-2026-1041",
    "date": "2026-06-22T10:49:17Z",
    "amount": 137800,
    "customer_name": "Vikram Malhotra",
    "customer_email": "vikram.m@techstart.io",
    "customer_city": "Gurugram",
    "region": "North",
    "product_id": "PRD-104",
    "product_name": "Dell UltraSharp 32-inch 4K USB-C Monitor",
    "category": "Electronics",
    "quantity": 2,
    "unit_price": 68900,
    "discount": 0,
    "salesperson": "Rahul Verma",
    "payment_method": "Credit Card",
    "status": "refunded",
    "notes": "Commercial transaction via Credit Card"
  },
  {
    "id": 110,
    "order_id": "ORD-2026-1110",
    "date": "2026-06-20T18:18:44Z",
    "amount": 137800,
    "customer_name": "Kolkata Port Logistics",
    "customer_email": "ops@kplogistics.in",
    "customer_city": "Kolkata",
    "region": "East",
    "product_id": "PRD-104",
    "product_name": "Dell UltraSharp 32-inch 4K USB-C Monitor",
    "category": "Electronics",
    "quantity": 2,
    "unit_price": 68900,
    "discount": 0,
    "salesperson": "Deepak Nair",
    "payment_method": "UPI",
    "status": "completed",
    "notes": "Commercial transaction via UPI"
  },
  {
    "id": 42,
    "order_id": "ORD-2026-1042",
    "date": "2026-06-20T13:11:37Z",
    "amount": 42000,
    "customer_name": "Kolkata Port Logistics",
    "customer_email": "ops@kplogistics.in",
    "customer_city": "Kolkata",
    "region": "East",
    "product_id": "PRD-106",
    "product_name": "Standing Electric Desk Pro",
    "category": "Furniture",
    "quantity": 1,
    "unit_price": 42000,
    "discount": 0,
    "salesperson": "Rohan Mehta",
    "payment_method": "Net Banking",
    "status": "completed",
    "notes": "Commercial transaction via Net Banking"
  },
  {
    "id": 111,
    "order_id": "ORD-2026-1111",
    "date": "2026-06-19T20:31:53Z",
    "amount": 49999,
    "customer_name": "Reliance Retail Ltd",
    "customer_email": "procurement@reliance.in",
    "customer_city": "Mumbai",
    "region": "West",
    "product_id": "PRD-105",
    "product_name": "SalesPulse CRM Enterprise License",
    "category": "SaaS Software",
    "quantity": 1,
    "unit_price": 49999,
    "discount": 0,
    "salesperson": "Deepak Nair",
    "payment_method": "Net Banking",
    "status": "completed",
    "notes": "Commercial transaction via Net Banking"
  },
  {
    "id": 43,
    "order_id": "ORD-2026-1043",
    "date": "2026-06-19T14:27:38Z",
    "amount": 49999,
    "customer_name": "Tata Consultancy Services",
    "customer_email": "infra.buy@tcs.com",
    "customer_city": "Mumbai",
    "region": "West",
    "product_id": "PRD-105",
    "product_name": "SalesPulse CRM Enterprise License",
    "category": "SaaS Software",
    "quantity": 1,
    "unit_price": 49999,
    "discount": 0,
    "salesperson": "Rahul Verma",
    "payment_method": "Bank Transfer",
    "status": "refunded",
    "notes": "Commercial transaction via Bank Transfer"
  },
  {
    "id": 112,
    "order_id": "ORD-2026-1112",
    "date": "2026-06-17T19:48:46Z",
    "amount": 49999,
    "customer_name": "Vikram Malhotra",
    "customer_email": "vikram.m@techstart.io",
    "customer_city": "Gurugram",
    "region": "North",
    "product_id": "PRD-105",
    "product_name": "SalesPulse CRM Enterprise License",
    "category": "SaaS Software",
    "quantity": 1,
    "unit_price": 49999,
    "discount": 0,
    "salesperson": "Rohan Mehta",
    "payment_method": "Net Banking",
    "status": "completed",
    "notes": "Commercial transaction via Net Banking"
  },
  {
    "id": 44,
    "order_id": "ORD-2026-1044",
    "date": "2026-06-17T09:33:59Z",
    "amount": 38246,
    "customer_name": "HDFC Financial Services",
    "customer_email": "it.assets@hdfcbank.com",
    "customer_city": "Mumbai",
    "region": "West",
    "product_id": "PRD-109",
    "product_name": "Anker PowerStation 100W Fast Charger",
    "category": "Accessories",
    "quantity": 5,
    "unit_price": 8499,
    "discount": 4249,
    "salesperson": "Deepak Nair",
    "payment_method": "Bank Transfer",
    "status": "completed",
    "notes": "Commercial transaction via Bank Transfer"
  },
  {
    "id": 45,
    "order_id": "ORD-2026-1045",
    "date": "2026-06-16T18:20:42Z",
    "amount": 93489,
    "customer_name": "Priya Patel Enterprises",
    "customer_email": "priya@pateldesign.co",
    "customer_city": "Ahmedabad",
    "region": "West",
    "product_id": "PRD-109",
    "product_name": "Anker PowerStation 100W Fast Charger",
    "category": "Accessories",
    "quantity": 11,
    "unit_price": 8499,
    "discount": 0,
    "salesperson": "Kavita Rao",
    "payment_method": "Debit Card",
    "status": "completed",
    "notes": "Commercial transaction via Debit Card"
  },
  {
    "id": 113,
    "order_id": "ORD-2026-1113",
    "date": "2026-06-15T20:08:05Z",
    "amount": 135000,
    "customer_name": "Wipro Technologies",
    "customer_email": "tech.orders@wipro.com",
    "customer_city": "Bengaluru",
    "region": "South",
    "product_id": "PRD-111",
    "product_name": "Data Analytics Pipeline Connector Pro",
    "category": "SaaS Software",
    "quantity": 2,
    "unit_price": 75000,
    "discount": 15000,
    "salesperson": "Rahul Verma",
    "payment_method": "UPI",
    "status": "pending",
    "notes": "Commercial transaction via UPI"
  },
  {
    "id": 46,
    "order_id": "ORD-2026-1046",
    "date": "2026-06-14T13:35:08Z",
    "amount": 185000,
    "customer_name": "Zomato Media Pvt Ltd",
    "customer_email": "infra@zomato.com",
    "customer_city": "Gurugram",
    "region": "North",
    "product_id": "PRD-102",
    "product_name": "Enterprise AI Cloud Subscription Annual",
    "category": "SaaS Software",
    "quantity": 1,
    "unit_price": 185000,
    "discount": 0,
    "salesperson": "Rohan Mehta",
    "payment_method": "Net Banking",
    "status": "refunded",
    "notes": "Commercial transaction via Net Banking"
  },
  {
    "id": 114,
    "order_id": "ORD-2026-1114",
    "date": "2026-06-13T14:33:32Z",
    "amount": 49999,
    "customer_name": "Razorpay Tech Labs",
    "customer_email": "hardware@razorpay.com",
    "customer_city": "Bengaluru",
    "region": "South",
    "product_id": "PRD-105",
    "product_name": "SalesPulse CRM Enterprise License",
    "category": "SaaS Software",
    "quantity": 1,
    "unit_price": 49999,
    "discount": 0,
    "salesperson": "Deepak Nair",
    "payment_method": "Credit Card",
    "status": "completed",
    "notes": "Commercial transaction via Credit Card"
  },
  {
    "id": 115,
    "order_id": "ORD-2026-1115",
    "date": "2026-06-12T16:04:09Z",
    "amount": 49999,
    "customer_name": "Aarav Sharma",
    "customer_email": "aarav.s@gmail.com",
    "customer_city": "Delhi",
    "region": "North",
    "product_id": "PRD-105",
    "product_name": "SalesPulse CRM Enterprise License",
    "category": "SaaS Software",
    "quantity": 1,
    "unit_price": 49999,
    "discount": 0,
    "salesperson": "Kavita Rao",
    "payment_method": "Debit Card",
    "status": "pending",
    "notes": "Commercial transaction via Debit Card"
  },
  {
    "id": 47,
    "order_id": "ORD-2026-1047",
    "date": "2026-06-12T09:19:18Z",
    "amount": 137800,
    "customer_name": "Bhubaneswar Softworks",
    "customer_email": "contact@bbsrsoft.com",
    "customer_city": "Bhubaneswar",
    "region": "East",
    "product_id": "PRD-104",
    "product_name": "Dell UltraSharp 32-inch 4K USB-C Monitor",
    "category": "Electronics",
    "quantity": 2,
    "unit_price": 68900,
    "discount": 0,
    "salesperson": "Deepak Nair",
    "payment_method": "Credit Card",
    "status": "pending",
    "notes": "Commercial transaction via Credit Card"
  },
  {
    "id": 48,
    "order_id": "ORD-2026-1048",
    "date": "2026-06-11T19:13:32Z",
    "amount": 137800,
    "customer_name": "Bhubaneswar Softworks",
    "customer_email": "contact@bbsrsoft.com",
    "customer_city": "Bhubaneswar",
    "region": "East",
    "product_id": "PRD-104",
    "product_name": "Dell UltraSharp 32-inch 4K USB-C Monitor",
    "category": "Electronics",
    "quantity": 2,
    "unit_price": 68900,
    "discount": 0,
    "salesperson": "Rohan Mehta",
    "payment_method": "Bank Transfer",
    "status": "completed",
    "notes": "Commercial transaction via Bank Transfer"
  },
  {
    "id": 116,
    "order_id": "ORD-2026-1116",
    "date": "2026-06-10T10:29:23Z",
    "amount": 117130,
    "customer_name": "Kolkata Port Logistics",
    "customer_email": "ops@kplogistics.in",
    "customer_city": "Kolkata",
    "region": "East",
    "product_id": "PRD-104",
    "product_name": "Dell UltraSharp 32-inch 4K USB-C Monitor",
    "category": "Electronics",
    "quantity": 2,
    "unit_price": 68900,
    "discount": 20670,
    "salesperson": "Rohan Mehta",
    "payment_method": "Net Banking",
    "status": "completed",
    "notes": "Commercial transaction via Net Banking"
  },
  {
    "id": 49,
    "order_id": "ORD-2026-1049",
    "date": "2026-06-09T12:43:19Z",
    "amount": 37980,
    "customer_name": "Aarav Sharma",
    "customer_email": "aarav.s@gmail.com",
    "customer_city": "Delhi",
    "region": "North",
    "product_id": "PRD-108",
    "product_name": "Logitech MX Master 3S Combo",
    "category": "Accessories",
    "quantity": 2,
    "unit_price": 18990,
    "discount": 0,
    "salesperson": "Rahul Verma",
    "payment_method": "Net Banking",
    "status": "completed",
    "notes": "Commercial transaction via Net Banking"
  },
  {
    "id": 50,
    "order_id": "ORD-2026-1050",
    "date": "2026-06-08T18:54:49Z",
    "amount": 68900,
    "customer_name": "Priya Patel Enterprises",
    "customer_email": "priya@pateldesign.co",
    "customer_city": "Ahmedabad",
    "region": "West",
    "product_id": "PRD-104",
    "product_name": "Dell UltraSharp 32-inch 4K USB-C Monitor",
    "category": "Electronics",
    "quantity": 1,
    "unit_price": 68900,
    "discount": 0,
    "salesperson": "Ananya Sen",
    "payment_method": "UPI",
    "status": "completed",
    "notes": "Commercial transaction via UPI"
  },
  {
    "id": 117,
    "order_id": "ORD-2026-1117",
    "date": "2026-06-08T16:01:39Z",
    "amount": 75000,
    "customer_name": "Ananya Iyer",
    "customer_email": "ananya.iyer@creativestudio.in",
    "customer_city": "Chennai",
    "region": "South",
    "product_id": "PRD-111",
    "product_name": "Data Analytics Pipeline Connector Pro",
    "category": "SaaS Software",
    "quantity": 1,
    "unit_price": 75000,
    "discount": 0,
    "salesperson": "Rohan Mehta",
    "payment_method": "Debit Card",
    "status": "completed",
    "notes": "Commercial transaction via Debit Card"
  },
  {
    "id": 118,
    "order_id": "ORD-2026-1118",
    "date": "2026-06-06T20:19:41Z",
    "amount": 93489,
    "customer_name": "Razorpay Tech Labs",
    "customer_email": "hardware@razorpay.com",
    "customer_city": "Bengaluru",
    "region": "South",
    "product_id": "PRD-109",
    "product_name": "Anker PowerStation 100W Fast Charger",
    "category": "Accessories",
    "quantity": 11,
    "unit_price": 8499,
    "discount": 0,
    "salesperson": "Rohan Mehta",
    "payment_method": "Credit Card",
    "status": "completed",
    "notes": "Commercial transaction via Credit Card"
  },
  {
    "id": 51,
    "order_id": "ORD-2026-1051",
    "date": "2026-06-06T12:09:41Z",
    "amount": 185000,
    "customer_name": "Naveen Gupta",
    "customer_email": "naveen.gupta@consultant.in",
    "customer_city": "Noida",
    "region": "North",
    "product_id": "PRD-102",
    "product_name": "Enterprise AI Cloud Subscription Annual",
    "category": "SaaS Software",
    "quantity": 1,
    "unit_price": 185000,
    "discount": 0,
    "salesperson": "Deepak Nair",
    "payment_method": "Bank Transfer",
    "status": "completed",
    "notes": "Commercial transaction via Bank Transfer"
  },
  {
    "id": 119,
    "order_id": "ORD-2026-1119",
    "date": "2026-06-05T10:06:15Z",
    "amount": 89970,
    "customer_name": "HDFC Financial Services",
    "customer_email": "it.assets@hdfcbank.com",
    "customer_city": "Mumbai",
    "region": "West",
    "product_id": "PRD-107",
    "product_name": "Sony WH-1000XM5 Wireless Headphones",
    "category": "Audio",
    "quantity": 3,
    "unit_price": 29990,
    "discount": 0,
    "salesperson": "Ananya Sen",
    "payment_method": "UPI",
    "status": "completed",
    "notes": "Commercial transaction via UPI"
  },
  {
    "id": 52,
    "order_id": "ORD-2026-1052",
    "date": "2026-06-04T20:33:29Z",
    "amount": 69900,
    "customer_name": "Reliance Retail Ltd",
    "customer_email": "procurement@reliance.in",
    "customer_city": "Mumbai",
    "region": "West",
    "product_id": "PRD-112",
    "product_name": "Apple iPad Air M2 256GB",
    "category": "Electronics",
    "quantity": 1,
    "unit_price": 69900,
    "discount": 0,
    "salesperson": "Rahul Verma",
    "payment_method": "Debit Card",
    "status": "completed",
    "notes": "Commercial transaction via Debit Card"
  },
  {
    "id": 120,
    "order_id": "ORD-2026-1120",
    "date": "2026-06-03T20:34:26Z",
    "amount": 93489,
    "customer_name": "Wipro Technologies",
    "customer_email": "tech.orders@wipro.com",
    "customer_city": "Bengaluru",
    "region": "South",
    "product_id": "PRD-109",
    "product_name": "Anker PowerStation 100W Fast Charger",
    "category": "Accessories",
    "quantity": 11,
    "unit_price": 8499,
    "discount": 0,
    "salesperson": "Deepak Nair",
    "payment_method": "Debit Card",
    "status": "completed",
    "notes": "Commercial transaction via Debit Card"
  },
  {
    "id": 53,
    "order_id": "ORD-2026-1053",
    "date": "2026-06-03T17:38:20Z",
    "amount": 319900,
    "customer_name": "Vikram Malhotra",
    "customer_email": "vikram.m@techstart.io",
    "customer_city": "Gurugram",
    "region": "North",
    "product_id": "PRD-101",
    "product_name": "MacBook Pro M3 Max 16-inch",
    "category": "Electronics",
    "quantity": 1,
    "unit_price": 319900,
    "discount": 0,
    "salesperson": "Rahul Verma",
    "payment_method": "Debit Card",
    "status": "completed",
    "notes": "Commercial transaction via Debit Card"
  },
  {
    "id": 121,
    "order_id": "ORD-2026-1121",
    "date": "2026-06-01T13:02:44Z",
    "amount": 98000,
    "customer_name": "Wipro Technologies",
    "customer_email": "tech.orders@wipro.com",
    "customer_city": "Bengaluru",
    "region": "South",
    "product_id": "PRD-110",
    "product_name": "Bose SoundLink Revolve II Speaker",
    "category": "Audio",
    "quantity": 4,
    "unit_price": 24500,
    "discount": 0,
    "salesperson": "Deepak Nair",
    "payment_method": "UPI",
    "status": "cancelled",
    "notes": "Commercial transaction via UPI"
  },
  {
    "id": 54,
    "order_id": "ORD-2026-1054",
    "date": "2026-06-01T12:53:40Z",
    "amount": 151920,
    "customer_name": "Bhubaneswar Softworks",
    "customer_email": "contact@bbsrsoft.com",
    "customer_city": "Bhubaneswar",
    "region": "East",
    "product_id": "PRD-108",
    "product_name": "Logitech MX Master 3S Combo",
    "category": "Accessories",
    "quantity": 8,
    "unit_price": 18990,
    "discount": 0,
    "salesperson": "Rohan Mehta",
    "payment_method": "Debit Card",
    "status": "completed",
    "notes": "Commercial transaction via Debit Card"
  },
  {
    "id": 122,
    "order_id": "ORD-2026-1122",
    "date": "2026-05-30T14:34:57Z",
    "amount": 71400,
    "customer_name": "Priya Patel Enterprises",
    "customer_email": "priya@pateldesign.co",
    "customer_city": "Ahmedabad",
    "region": "West",
    "product_id": "PRD-106",
    "product_name": "Standing Electric Desk Pro",
    "category": "Furniture",
    "quantity": 2,
    "unit_price": 42000,
    "discount": 12600,
    "salesperson": "Deepak Nair",
    "payment_method": "Debit Card",
    "status": "completed",
    "notes": "Commercial transaction via Debit Card"
  },
  {
    "id": 55,
    "order_id": "ORD-2026-1055",
    "date": "2026-05-30T12:17:21Z",
    "amount": 49999,
    "customer_name": "Deepika Sen",
    "customer_email": "deepika.sen@designhub.in",
    "customer_city": "Kolkata",
    "region": "East",
    "product_id": "PRD-105",
    "product_name": "SalesPulse CRM Enterprise License",
    "category": "SaaS Software",
    "quantity": 1,
    "unit_price": 49999,
    "discount": 0,
    "salesperson": "Ananya Sen",
    "payment_method": "Net Banking",
    "status": "cancelled",
    "notes": "Commercial transaction via Net Banking"
  },
  {
    "id": 56,
    "order_id": "ORD-2026-1056",
    "date": "2026-05-29T20:13:04Z",
    "amount": 84000,
    "customer_name": "Infosys Digital Labs",
    "customer_email": "vendor@infosys.com",
    "customer_city": "Bengaluru",
    "region": "South",
    "product_id": "PRD-106",
    "product_name": "Standing Electric Desk Pro",
    "category": "Furniture",
    "quantity": 2,
    "unit_price": 42000,
    "discount": 0,
    "salesperson": "Ananya Sen",
    "payment_method": "Credit Card",
    "status": "completed",
    "notes": "Commercial transaction via Credit Card"
  },
  {
    "id": 123,
    "order_id": "ORD-2026-1123",
    "date": "2026-05-28T16:05:42Z",
    "amount": 75000,
    "customer_name": "Apollo Health Logistics",
    "customer_email": "supply@apollohealth.org",
    "customer_city": "Hyderabad",
    "region": "South",
    "product_id": "PRD-111",
    "product_name": "Data Analytics Pipeline Connector Pro",
    "category": "SaaS Software",
    "quantity": 1,
    "unit_price": 75000,
    "discount": 0,
    "salesperson": "Rahul Verma",
    "payment_method": "Debit Card",
    "status": "pending",
    "notes": "Commercial transaction via Debit Card"
  },
  {
    "id": 57,
    "order_id": "ORD-2026-1057",
    "date": "2026-05-27T15:57:49Z",
    "amount": 107964,
    "customer_name": "Bhubaneswar Softworks",
    "customer_email": "contact@bbsrsoft.com",
    "customer_city": "Bhubaneswar",
    "region": "East",
    "product_id": "PRD-107",
    "product_name": "Sony WH-1000XM5 Wireless Headphones",
    "category": "Audio",
    "quantity": 4,
    "unit_price": 29990,
    "discount": 11996,
    "salesperson": "Kavita Rao",
    "payment_method": "Bank Transfer",
    "status": "cancelled",
    "notes": "Commercial transaction via Bank Transfer"
  },
  {
    "id": 124,
    "order_id": "ORD-2026-1124",
    "date": "2026-05-27T12:04:53Z",
    "amount": 68900,
    "customer_name": "Reliance Retail Ltd",
    "customer_email": "procurement@reliance.in",
    "customer_city": "Mumbai",
    "region": "West",
    "product_id": "PRD-104",
    "product_name": "Dell UltraSharp 32-inch 4K USB-C Monitor",
    "category": "Electronics",
    "quantity": 1,
    "unit_price": 68900,
    "discount": 0,
    "salesperson": "Rahul Verma",
    "payment_method": "Net Banking",
    "status": "completed",
    "notes": "Commercial transaction via Net Banking"
  },
  {
    "id": 125,
    "order_id": "ORD-2026-1125",
    "date": "2026-05-25T18:00:17Z",
    "amount": 50994,
    "customer_name": "Priya Patel Enterprises",
    "customer_email": "priya@pateldesign.co",
    "customer_city": "Ahmedabad",
    "region": "West",
    "product_id": "PRD-109",
    "product_name": "Anker PowerStation 100W Fast Charger",
    "category": "Accessories",
    "quantity": 6,
    "unit_price": 8499,
    "discount": 0,
    "salesperson": "Rohan Mehta",
    "payment_method": "Credit Card",
    "status": "completed",
    "notes": "Commercial transaction via Credit Card"
  },
  {
    "id": 58,
    "order_id": "ORD-2026-1058",
    "date": "2026-05-25T13:48:24Z",
    "amount": 24500,
    "customer_name": "Reliance Retail Ltd",
    "customer_email": "procurement@reliance.in",
    "customer_city": "Mumbai",
    "region": "West",
    "product_id": "PRD-110",
    "product_name": "Bose SoundLink Revolve II Speaker",
    "category": "Audio",
    "quantity": 1,
    "unit_price": 24500,
    "discount": 0,
    "salesperson": "Rohan Mehta",
    "payment_method": "Debit Card",
    "status": "cancelled",
    "notes": "Commercial transaction via Debit Card"
  },
  {
    "id": 59,
    "order_id": "ORD-2026-1059",
    "date": "2026-05-24T15:21:42Z",
    "amount": 119960,
    "customer_name": "Vikram Malhotra",
    "customer_email": "vikram.m@techstart.io",
    "customer_city": "Gurugram",
    "region": "North",
    "product_id": "PRD-107",
    "product_name": "Sony WH-1000XM5 Wireless Headphones",
    "category": "Audio",
    "quantity": 4,
    "unit_price": 29990,
    "discount": 0,
    "salesperson": "Deepak Nair",
    "payment_method": "Credit Card",
    "status": "pending",
    "notes": "Commercial transaction via Credit Card"
  },
  {
    "id": 126,
    "order_id": "ORD-2026-1126",
    "date": "2026-05-23T09:08:00Z",
    "amount": 84500,
    "customer_name": "Wipro Technologies",
    "customer_email": "tech.orders@wipro.com",
    "customer_city": "Bengaluru",
    "region": "South",
    "product_id": "PRD-103",
    "product_name": "Ergonomic Herman Miller Chair",
    "category": "Furniture",
    "quantity": 1,
    "unit_price": 84500,
    "discount": 0,
    "salesperson": "Rohan Mehta",
    "payment_method": "Net Banking",
    "status": "completed",
    "notes": "Commercial transaction via Net Banking"
  },
  {
    "id": 60,
    "order_id": "ORD-2026-1060",
    "date": "2026-05-22T18:36:42Z",
    "amount": 75000,
    "customer_name": "Kolkata Port Logistics",
    "customer_email": "ops@kplogistics.in",
    "customer_city": "Kolkata",
    "region": "East",
    "product_id": "PRD-111",
    "product_name": "Data Analytics Pipeline Connector Pro",
    "category": "SaaS Software",
    "quantity": 1,
    "unit_price": 75000,
    "discount": 0,
    "salesperson": "Ananya Sen",
    "payment_method": "Debit Card",
    "status": "completed",
    "notes": "Commercial transaction via Debit Card"
  },
  {
    "id": 127,
    "order_id": "ORD-2026-1127",
    "date": "2026-05-21T11:47:26Z",
    "amount": 42000,
    "customer_name": "Vikram Malhotra",
    "customer_email": "vikram.m@techstart.io",
    "customer_city": "Gurugram",
    "region": "North",
    "product_id": "PRD-106",
    "product_name": "Standing Electric Desk Pro",
    "category": "Furniture",
    "quantity": 1,
    "unit_price": 42000,
    "discount": 0,
    "salesperson": "Rohan Mehta",
    "payment_method": "Net Banking",
    "status": "completed",
    "notes": "Commercial transaction via Net Banking"
  },
  {
    "id": 61,
    "order_id": "ORD-2026-1061",
    "date": "2026-05-20T14:13:29Z",
    "amount": 287910,
    "customer_name": "Infosys Digital Labs",
    "customer_email": "vendor@infosys.com",
    "customer_city": "Bengaluru",
    "region": "South",
    "product_id": "PRD-101",
    "product_name": "MacBook Pro M3 Max 16-inch",
    "category": "Electronics",
    "quantity": 1,
    "unit_price": 319900,
    "discount": 31990,
    "salesperson": "Deepak Nair",
    "payment_method": "Credit Card",
    "status": "cancelled",
    "notes": "Commercial transaction via Credit Card"
  },
  {
    "id": 128,
    "order_id": "ORD-2026-1128",
    "date": "2026-05-20T10:28:32Z",
    "amount": 50994,
    "customer_name": "HDFC Financial Services",
    "customer_email": "it.assets@hdfcbank.com",
    "customer_city": "Mumbai",
    "region": "West",
    "product_id": "PRD-109",
    "product_name": "Anker PowerStation 100W Fast Charger",
    "category": "Accessories",
    "quantity": 6,
    "unit_price": 8499,
    "discount": 0,
    "salesperson": "Rahul Verma",
    "payment_method": "Debit Card",
    "status": "cancelled",
    "notes": "Commercial transaction via Debit Card"
  },
  {
    "id": 62,
    "order_id": "ORD-2026-1062",
    "date": "2026-05-19T16:01:47Z",
    "amount": 84000,
    "customer_name": "Razorpay Tech Labs",
    "customer_email": "hardware@razorpay.com",
    "customer_city": "Bengaluru",
    "region": "South",
    "product_id": "PRD-106",
    "product_name": "Standing Electric Desk Pro",
    "category": "Furniture",
    "quantity": 2,
    "unit_price": 42000,
    "discount": 0,
    "salesperson": "Deepak Nair",
    "payment_method": "Net Banking",
    "status": "refunded",
    "notes": "Commercial transaction via Net Banking"
  },
  {
    "id": 129,
    "order_id": "ORD-2026-1129",
    "date": "2026-05-18T09:30:54Z",
    "amount": 206700,
    "customer_name": "Tata Consultancy Services",
    "customer_email": "infra.buy@tcs.com",
    "customer_city": "Mumbai",
    "region": "West",
    "product_id": "PRD-104",
    "product_name": "Dell UltraSharp 32-inch 4K USB-C Monitor",
    "category": "Electronics",
    "quantity": 3,
    "unit_price": 68900,
    "discount": 0,
    "salesperson": "Rohan Mehta",
    "payment_method": "Net Banking",
    "status": "cancelled",
    "notes": "Commercial transaction via Net Banking"
  },
  {
    "id": 63,
    "order_id": "ORD-2026-1063",
    "date": "2026-05-17T12:12:53Z",
    "amount": 88815,
    "customer_name": "Tata Consultancy Services",
    "customer_email": "infra.buy@tcs.com",
    "customer_city": "Mumbai",
    "region": "West",
    "product_id": "PRD-109",
    "product_name": "Anker PowerStation 100W Fast Charger",
    "category": "Accessories",
    "quantity": 11,
    "unit_price": 8499,
    "discount": 4674,
    "salesperson": "Kavita Rao",
    "payment_method": "Credit Card",
    "status": "completed",
    "notes": "Commercial transaction via Credit Card"
  },
  {
    "id": 130,
    "order_id": "ORD-2026-1130",
    "date": "2026-05-16T14:38:09Z",
    "amount": 29990,
    "customer_name": "Bhubaneswar Softworks",
    "customer_email": "contact@bbsrsoft.com",
    "customer_city": "Bhubaneswar",
    "region": "East",
    "product_id": "PRD-107",
    "product_name": "Sony WH-1000XM5 Wireless Headphones",
    "category": "Audio",
    "quantity": 1,
    "unit_price": 29990,
    "discount": 0,
    "salesperson": "Rahul Verma",
    "payment_method": "Debit Card",
    "status": "cancelled",
    "notes": "Commercial transaction via Debit Card"
  },
  {
    "id": 64,
    "order_id": "ORD-2026-1064",
    "date": "2026-05-15T12:29:44Z",
    "amount": 319900,
    "customer_name": "Wipro Technologies",
    "customer_email": "tech.orders@wipro.com",
    "customer_city": "Bengaluru",
    "region": "South",
    "product_id": "PRD-101",
    "product_name": "MacBook Pro M3 Max 16-inch",
    "category": "Electronics",
    "quantity": 1,
    "unit_price": 319900,
    "discount": 0,
    "salesperson": "Ananya Sen",
    "payment_method": "Credit Card",
    "status": "cancelled",
    "notes": "Commercial transaction via Credit Card"
  },
  {
    "id": 131,
    "order_id": "ORD-2026-1131",
    "date": "2026-05-14T17:18:29Z",
    "amount": 185000,
    "customer_name": "Wipro Technologies",
    "customer_email": "tech.orders@wipro.com",
    "customer_city": "Bengaluru",
    "region": "South",
    "product_id": "PRD-102",
    "product_name": "Enterprise AI Cloud Subscription Annual",
    "category": "SaaS Software",
    "quantity": 1,
    "unit_price": 185000,
    "discount": 0,
    "salesperson": "Kavita Rao",
    "payment_method": "Bank Transfer",
    "status": "completed",
    "notes": "Commercial transaction via Bank Transfer"
  },
  {
    "id": 65,
    "order_id": "ORD-2026-1065",
    "date": "2026-05-14T10:37:01Z",
    "amount": 49999,
    "customer_name": "Apollo Health Logistics",
    "customer_email": "supply@apollohealth.org",
    "customer_city": "Hyderabad",
    "region": "South",
    "product_id": "PRD-105",
    "product_name": "SalesPulse CRM Enterprise License",
    "category": "SaaS Software",
    "quantity": 1,
    "unit_price": 49999,
    "discount": 0,
    "salesperson": "Ananya Sen",
    "payment_method": "Bank Transfer",
    "status": "completed",
    "notes": "Commercial transaction via Bank Transfer"
  },
  {
    "id": 66,
    "order_id": "ORD-2026-1066",
    "date": "2026-05-12T19:38:51Z",
    "amount": 45000,
    "customer_name": "Kolkata Port Logistics",
    "customer_email": "ops@kplogistics.in",
    "customer_city": "Kolkata",
    "region": "East",
    "product_id": "PRD-105",
    "product_name": "SalesPulse CRM Enterprise License",
    "category": "SaaS Software",
    "quantity": 1,
    "unit_price": 49999,
    "discount": 4999,
    "salesperson": "Deepak Nair",
    "payment_method": "Credit Card",
    "status": "completed",
    "notes": "Commercial transaction via Credit Card"
  },
  {
    "id": 132,
    "order_id": "ORD-2026-1132",
    "date": "2026-05-12T12:26:21Z",
    "amount": 59493,
    "customer_name": "Bhubaneswar Softworks",
    "customer_email": "contact@bbsrsoft.com",
    "customer_city": "Bhubaneswar",
    "region": "East",
    "product_id": "PRD-109",
    "product_name": "Anker PowerStation 100W Fast Charger",
    "category": "Accessories",
    "quantity": 7,
    "unit_price": 8499,
    "discount": 0,
    "salesperson": "Rahul Verma",
    "payment_method": "UPI",
    "status": "completed",
    "notes": "Commercial transaction via UPI"
  },
  {
    "id": 133,
    "order_id": "ORD-2026-1133",
    "date": "2026-05-11T13:23:09Z",
    "amount": 132930,
    "customer_name": "Kolkata Port Logistics",
    "customer_email": "ops@kplogistics.in",
    "customer_city": "Kolkata",
    "region": "East",
    "product_id": "PRD-108",
    "product_name": "Logitech MX Master 3S Combo",
    "category": "Accessories",
    "quantity": 7,
    "unit_price": 18990,
    "discount": 0,
    "salesperson": "Deepak Nair",
    "payment_method": "UPI",
    "status": "completed",
    "notes": "Commercial transaction via UPI"
  },
  {
    "id": 67,
    "order_id": "ORD-2026-1067",
    "date": "2026-05-10T14:00:54Z",
    "amount": 157250,
    "customer_name": "Tata Consultancy Services",
    "customer_email": "infra.buy@tcs.com",
    "customer_city": "Mumbai",
    "region": "West",
    "product_id": "PRD-102",
    "product_name": "Enterprise AI Cloud Subscription Annual",
    "category": "SaaS Software",
    "quantity": 1,
    "unit_price": 185000,
    "discount": 27750,
    "salesperson": "Kavita Rao",
    "payment_method": "Bank Transfer",
    "status": "refunded",
    "notes": "Commercial transaction via Bank Transfer"
  },
  {
    "id": 134,
    "order_id": "ORD-2026-1134",
    "date": "2026-05-09T20:47:23Z",
    "amount": 75000,
    "customer_name": "Deepika Sen",
    "customer_email": "deepika.sen@designhub.in",
    "customer_city": "Kolkata",
    "region": "East",
    "product_id": "PRD-111",
    "product_name": "Data Analytics Pipeline Connector Pro",
    "category": "SaaS Software",
    "quantity": 1,
    "unit_price": 75000,
    "discount": 0,
    "salesperson": "Rahul Verma",
    "payment_method": "UPI",
    "status": "completed",
    "notes": "Commercial transaction via UPI"
  },
  {
    "id": 68,
    "order_id": "ORD-2026-1068",
    "date": "2026-05-09T15:11:46Z",
    "amount": 119960,
    "customer_name": "Deepika Sen",
    "customer_email": "deepika.sen@designhub.in",
    "customer_city": "Kolkata",
    "region": "East",
    "product_id": "PRD-107",
    "product_name": "Sony WH-1000XM5 Wireless Headphones",
    "category": "Audio",
    "quantity": 4,
    "unit_price": 29990,
    "discount": 0,
    "salesperson": "Rahul Verma",
    "payment_method": "Debit Card",
    "status": "completed",
    "notes": "Commercial transaction via Debit Card"
  },
  {
    "id": 69,
    "order_id": "ORD-2026-1069",
    "date": "2026-05-07T20:37:17Z",
    "amount": 67992,
    "customer_name": "Ananya Iyer",
    "customer_email": "ananya.iyer@creativestudio.in",
    "customer_city": "Chennai",
    "region": "South",
    "product_id": "PRD-109",
    "product_name": "Anker PowerStation 100W Fast Charger",
    "category": "Accessories",
    "quantity": 8,
    "unit_price": 8499,
    "discount": 0,
    "salesperson": "Rohan Mehta",
    "payment_method": "Bank Transfer",
    "status": "cancelled",
    "notes": "Commercial transaction via Bank Transfer"
  },
  {
    "id": 135,
    "order_id": "ORD-2026-1135",
    "date": "2026-05-07T19:48:27Z",
    "amount": 84500,
    "customer_name": "Tata Consultancy Services",
    "customer_email": "infra.buy@tcs.com",
    "customer_city": "Mumbai",
    "region": "West",
    "product_id": "PRD-103",
    "product_name": "Ergonomic Herman Miller Chair",
    "category": "Furniture",
    "quantity": 1,
    "unit_price": 84500,
    "discount": 0,
    "salesperson": "Rohan Mehta",
    "payment_method": "Bank Transfer",
    "status": "completed",
    "notes": "Commercial transaction via Bank Transfer"
  },
  {
    "id": 70,
    "order_id": "ORD-2026-1070",
    "date": "2026-05-05T18:39:42Z",
    "amount": 42000,
    "customer_name": "Vikram Malhotra",
    "customer_email": "vikram.m@techstart.io",
    "customer_city": "Gurugram",
    "region": "North",
    "product_id": "PRD-106",
    "product_name": "Standing Electric Desk Pro",
    "category": "Furniture",
    "quantity": 1,
    "unit_price": 42000,
    "discount": 0,
    "salesperson": "Rahul Verma",
    "payment_method": "Net Banking",
    "status": "cancelled",
    "notes": "Commercial transaction via Net Banking"
  },
  {
    "id": 136,
    "order_id": "ORD-2026-1136",
    "date": "2026-05-05T12:09:42Z",
    "amount": 118830,
    "customer_name": "Tata Consultancy Services",
    "customer_email": "infra.buy@tcs.com",
    "customer_city": "Mumbai",
    "region": "West",
    "product_id": "PRD-112",
    "product_name": "Apple iPad Air M2 256GB",
    "category": "Electronics",
    "quantity": 2,
    "unit_price": 69900,
    "discount": 20970,
    "salesperson": "Kavita Rao",
    "payment_method": "Bank Transfer",
    "status": "pending",
    "notes": "Commercial transaction via Bank Transfer"
  },
  {
    "id": 71,
    "order_id": "ORD-2026-1071",
    "date": "2026-05-04T14:51:16Z",
    "amount": 59980,
    "customer_name": "Razorpay Tech Labs",
    "customer_email": "hardware@razorpay.com",
    "customer_city": "Bengaluru",
    "region": "South",
    "product_id": "PRD-107",
    "product_name": "Sony WH-1000XM5 Wireless Headphones",
    "category": "Audio",
    "quantity": 2,
    "unit_price": 29990,
    "discount": 0,
    "salesperson": "Rahul Verma",
    "payment_method": "Debit Card",
    "status": "completed",
    "notes": "Commercial transaction via Debit Card"
  },
  {
    "id": 137,
    "order_id": "ORD-2026-1137",
    "date": "2026-05-03T18:14:51Z",
    "amount": 37980,
    "customer_name": "Vikram Malhotra",
    "customer_email": "vikram.m@techstart.io",
    "customer_city": "Gurugram",
    "region": "North",
    "product_id": "PRD-108",
    "product_name": "Logitech MX Master 3S Combo",
    "category": "Accessories",
    "quantity": 2,
    "unit_price": 18990,
    "discount": 0,
    "salesperson": "Rahul Verma",
    "payment_method": "Net Banking",
    "status": "completed",
    "notes": "Commercial transaction via Net Banking"
  },
  {
    "id": 72,
    "order_id": "ORD-2026-1072",
    "date": "2026-05-02T15:31:35Z",
    "amount": 35700,
    "customer_name": "Ananya Iyer",
    "customer_email": "ananya.iyer@creativestudio.in",
    "customer_city": "Chennai",
    "region": "South",
    "product_id": "PRD-106",
    "product_name": "Standing Electric Desk Pro",
    "category": "Furniture",
    "quantity": 1,
    "unit_price": 42000,
    "discount": 6300,
    "salesperson": "Rohan Mehta",
    "payment_method": "Net Banking",
    "status": "completed",
    "notes": "Commercial transaction via Net Banking"
  },
  {
    "id": 138,
    "order_id": "ORD-2026-1138",
    "date": "2026-05-02T13:58:21Z",
    "amount": 59980,
    "customer_name": "Reliance Retail Ltd",
    "customer_email": "procurement@reliance.in",
    "customer_city": "Mumbai",
    "region": "West",
    "product_id": "PRD-107",
    "product_name": "Sony WH-1000XM5 Wireless Headphones",
    "category": "Audio",
    "quantity": 2,
    "unit_price": 29990,
    "discount": 0,
    "salesperson": "Rohan Mehta",
    "payment_method": "Net Banking",
    "status": "completed",
    "notes": "Commercial transaction via Net Banking"
  },
  {
    "id": 73,
    "order_id": "ORD-2026-1073",
    "date": "2026-04-30T15:44:15Z",
    "amount": 68900,
    "customer_name": "Deepika Sen",
    "customer_email": "deepika.sen@designhub.in",
    "customer_city": "Kolkata",
    "region": "East",
    "product_id": "PRD-104",
    "product_name": "Dell UltraSharp 32-inch 4K USB-C Monitor",
    "category": "Electronics",
    "quantity": 1,
    "unit_price": 68900,
    "discount": 0,
    "salesperson": "Deepak Nair",
    "payment_method": "Debit Card",
    "status": "completed",
    "notes": "Commercial transaction via Debit Card"
  },
  {
    "id": 139,
    "order_id": "ORD-2026-1139",
    "date": "2026-04-30T09:05:47Z",
    "amount": 35700,
    "customer_name": "Reliance Retail Ltd",
    "customer_email": "procurement@reliance.in",
    "customer_city": "Mumbai",
    "region": "West",
    "product_id": "PRD-106",
    "product_name": "Standing Electric Desk Pro",
    "category": "Furniture",
    "quantity": 1,
    "unit_price": 42000,
    "discount": 6300,
    "salesperson": "Ananya Sen",
    "payment_method": "Credit Card",
    "status": "refunded",
    "notes": "Commercial transaction via Credit Card"
  },
  {
    "id": 74,
    "order_id": "ORD-2026-1074",
    "date": "2026-04-29T17:21:22Z",
    "amount": 49999,
    "customer_name": "Apollo Health Logistics",
    "customer_email": "supply@apollohealth.org",
    "customer_city": "Hyderabad",
    "region": "South",
    "product_id": "PRD-105",
    "product_name": "SalesPulse CRM Enterprise License",
    "category": "SaaS Software",
    "quantity": 1,
    "unit_price": 49999,
    "discount": 0,
    "salesperson": "Deepak Nair",
    "payment_method": "Bank Transfer",
    "status": "completed",
    "notes": "Commercial transaction via Bank Transfer"
  },
  {
    "id": 140,
    "order_id": "ORD-2026-1140",
    "date": "2026-04-28T20:20:49Z",
    "amount": 45895,
    "customer_name": "Priya Patel Enterprises",
    "customer_email": "priya@pateldesign.co",
    "customer_city": "Ahmedabad",
    "region": "West",
    "product_id": "PRD-109",
    "product_name": "Anker PowerStation 100W Fast Charger",
    "category": "Accessories",
    "quantity": 6,
    "unit_price": 8499,
    "discount": 5099,
    "salesperson": "Deepak Nair",
    "payment_method": "Debit Card",
    "status": "cancelled",
    "notes": "Commercial transaction via Debit Card"
  }
];
